events { worker_connections 1024; }

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/s;

    # ВАЖНО: Добавляем резолвер Docker DNS, чтобы Nginx не падал
    resolver 127.0.0.11 valid=10s;

    upstream auth { server auth:3001; }
    upstream doctors { server doctors:3002; }
    # upstream appointment { server appointment:3003; }  <-- УБИРАЕМ STATIC UPSTREAM
    upstream payment { server payment:3004; }
    upstream graphql { server graphql-gateway:4000; }
    upstream analytics { server analytics:3006; }

    server {
        listen 3000;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';

        location = /auth/verify {
            internal;
            proxy_pass http://auth/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

        location /auth/ {
            set $upstream_auth "http://auth:3001";
            proxy_pass $upstream_auth;
        }

        location /doctors/ {
            set $upstream_doctors "http://doctors:3002";
            proxy_pass $upstream_doctors;
        }
        
        location /appointments/ {
            limit_req zone=api_limit burst=50 nodelay;
            set $upstream_appointment "http://appointment:3003";
            proxy_pass $upstream_appointment;
        }

        location /payments/ {
            set $upstream_payment "http://payment:3004";
            proxy_pass $upstream_payment;
        }
        location /graphql { proxy_pass http://graphql/graphql; }
        location /analytics/ { proxy_pass http://analytics/; }
    }
}